apiVersion: operator.gatekeeper.sh/v1alpha1
kind: Gatekeeper
metadata:
  name: gatekeeper
spec:
  # Add fields here
  image:
    image: docker.io/openpolicyagent/gatekeeper:v3.2.2
  audit:
    replicas: 1
    logLevel: INFO
  validatingWebhook: Enabled
  webhook:
    replicas: 2
    logLevel: INFO
