name: Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15' ]

    name: Image build and push
    steps:
    - name: Set Up Environment Variables
      env:
        REPO: quay.io/${{ secrets.QUAY_ACCOUNT_NAME }}
        IMG: gatekeeper-operator
      run: |
        echo "REPO=${REPO}" >> ${GITHUB_ENV}
        WORKFLOW_IMG="${REPO}/${IMG}"
        echo "WORKFLOW_IMG=${WORKFLOW_IMG}" >> ${GITHUB_ENV}
        echo "WORKFLOW_BUNDLE_IMG=${WORKFLOW_IMG}-bundle" >> ${GITHUB_ENV}
        echo "WORKFLOW_BUNDLE_INDEX_IMG=${WORKFLOW_IMG}-bundle-index" >> ${GITHUB_ENV}

    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: image=moby/buildkit:v0.8-beta
    - uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.WORKFLOW_IMG }}:latest
          ${{ env.WORKFLOW_IMG }}:master

    - name: Build and Push Bundle Image
      run: |
        make bundle-build VERSION=master
        docker tag ${WORKFLOW_BUNDLE_IMG}:master ${WORKFLOW_BUNDLE_IMG}:latest
        make docker-push IMG=${WORKFLOW_BUNDLE_IMG}:master
        make docker-push IMG=${WORKFLOW_BUNDLE_IMG}:latest

    - name: Set Up Go to Install OPM
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Build and Push Bundle Index Image
      run: |
        make bundle-index-build VERSION=master
        docker tag ${WORKFLOW_BUNDLE_INDEX_IMG}:master ${WORKFLOW_BUNDLE_INDEX_IMG}:latest
        make docker-push IMG=${WORKFLOW_BUNDLE_INDEX_IMG}:master
        make docker-push IMG=${WORKFLOW_BUNDLE_INDEX_IMG}:latest
